- name: Deploy generator
  hosts: sterner
  tasks:
    - name: Install dependencies
      become: yes
      yum:
        name: 
          - python3
          - python3-pip
    
    - name: Copy files
      become: yes
      copy:
        src: '{{ item }}'
        dest: /root/
        mode: 0755
      loop:
        - generator.py
        - logger.py
        - additional_domains.py
