- name: Deploy generator
  hosts: sterner
  tasks:
    - name: Install dependencies
      become: yes
      yum:
        name: 
          - python3
          - python3-pip
    
    - name: Install pip dependencies
      become: yes
      pip:
        executable: /usr/bin/pip3
        name: requests
        state: present
        
    - name: Create directory
      become: yes
      file:
        path: /opt/sinkhole-updater
        state: directory
        owner: root
    
    - name: Copy files
      become: yes
      copy:
        src: '{{ item }}'
        dest: /opt/sinkhole-updater/
        mode: 0755
      loop:
        - generator.py
        - additional_domains

    - name: Copy systemd unit file
      become: yes
      copy:
        src: sinkhole-updater.service
        dest: /etc/systemd/system/
    
    - name: Restart service
      become: yes
      systemd:
        name: sinkhole-updater
        state: restarted
        daemon-reload: yes
